name: sql_helper
description: Helper for SQFLite Plugin, SQFLiteHelper, Multi-platform, sqlite
version: 0.1.2
author: Brian Rodriguez<rzknairb@gmail.com>
homepage: https://github.com/rzkbrian/FlutterSQLHeper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.5
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

